# Generated by Django 5.0.4 on 2024-08-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
