# Generated by Django 5.0.4 on 2024-08-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_price',
        ),
    ]
