# Generated by Django 5.0.4 on 2024-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_item_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
