# Generated by Django 5.0.4 on 2024-08-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_item_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Budget Titlt')),
            ],
        ),
    ]
