# Generated by Django 5.0.4 on 2024-08-22 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_budget_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.budget_title'),
        ),
    ]
